name: DeployToInfinityFree

on:
  push:
    branches: [ dev ]

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4.2.2

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOSTNAME }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_DIRECTORY }}
        protocol: ftps
        port: ${{ secrets.FTP_PORT }}
        exclude: |
          **/.git*
          **/.git*/**
          **/vendor/**
          **composer.phar*
          **LocalSettings.php*
