on:
  push:
    branches: [ main ]

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOSTNAME }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_DIRECTORY }}
        state-name: .ftp-deploy-sync-state.json
        protocol: ftps
        exclude: |
          **/.git*
          **/.git*/**
          **/vendor/**
          **composer.phar*
          **LocalSettings.php*

    - name: Show deploy state (debug only)
      run: cat .ftp-deploy-sync-state.json || echo "No previous state"
